# Dependabot configuration for version updates
# Specify package ecosystems and their respective locations for manifests.

version: 2

updates:
  - package-ecosystem: "npm"  # Specify the package manager (e.g., npm, pip, etc.)
    directory: "/"             # Path to the package manifest
    schedule:
      interval: "weekly"       # Frequency of update checks
      day: "monday"            # Day of the week to check for updates
      time: "09:00"            # Time of day to check for updates (hh:mm)
      timezone: "UTC"          # Timezone for the scheduled checks